<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Khosruzs-MacBook-Pro.local" failures="1" tests="8" name="tests.WebTableTest" time="0.688" errors="0" timestamp="2025-10-12T21:56:48 EDT" skipped="7">
  <testcase classname="tests.WebTableTest" name="setUpClass" time="0.686">
    <failure message="expected [zSolution] but found [Login - zSolution]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [zSolution] but found [Login - zSolution]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at tests.WebTableTest.setUpClass(WebTableTest.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:180)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- setUpClass -->
  <system-out/>
  <testcase classname="tests.WebTableTest" name="testRowCount" time="0.000">
    <skipped/>
  </testcase> <!-- testRowCount -->
  <system-out/>
  <testcase classname="tests.WebTableTest" name="testFetchAndPrintData" time="0.001">
    <skipped/>
  </testcase> <!-- testFetchAndPrintData -->
  <system-out/>
  <testcase classname="tests.WebTableTest" name="testSearchSpecificRecord" time="0.000">
    <skipped/>
  </testcase> <!-- testSearchSpecificRecord -->
  <system-out/>
  <testcase classname="tests.WebTableTest" name="testAddNewRecordAndSearch" time="0.001">
    <skipped/>
  </testcase> <!-- testAddNewRecordAndSearch -->
  <system-out/>
  <testcase classname="tests.WebTableTest" name="testDeleteRecord" time="0.000">
    <skipped/>
  </testcase> <!-- testDeleteRecord -->
  <system-out/>
  <testcase classname="tests.WebTableTest" name="testFilterByLocation" time="0.000">
    <skipped/>
  </testcase> <!-- testFilterByLocation -->
  <system-out/>
  <testcase classname="tests.WebTableTest" name="testDynamicRoleValidation" time="0.000">
    <skipped/>
  </testcase> <!-- testDynamicRoleValidation -->
  <system-out/>
</testsuite> <!-- tests.WebTableTest -->
